# Copyright 2025 The Outline Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

version: '3'

requires:
  vars: [OUTPUT_DIR]

tasks:
  android:configure:
    desc: Auto-configures the environment for Android development
    vars:
      DOTENV: '{{joinPath .OUTPUT_DIR "android" ".env"}}'
    generates:
      - '{{.DOTENV}}'
    cmds:
      - mkdir -p '{{dir .DOTENV}}'
      - '{{joinPath .TASKFILE_DIR "build" "configure_android.sh"}} > "{{.DOTENV}}"'
