module.exports = {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'scope-enum': [
      2,
      'always',
      [
        'client',
        'client/cordova',
        'client/cordova/android',
        'client/cordova/apple',
        'client/cordova/apple/ios',
        'client/cordova/apple/macos',
        'client/electron',
        'client/electron/linux',
        'client/electron/windows',
        'devtools',
        'docs',
        'infrastructure',
        'infrastructure/build',
        'manager',
        'manager/electron',
        'manager/electron/linux',
        'manager/electron/mac',
        'manager/electron/windows',
        'service',
        'service/linux',
        'service/windows',
        'storybook',
        'www',
      ],
    ],
    'type-enum': [
      2,
      'always',
      ['build', 'chore', 'ci', 'docs', 'feat', 'fix', 'perf', 'proposal', 'refactor', 'revert', 'style', 'test'],
    ],
  },
};
