# Copyright 2024 The Outline Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

version: '3'

set: [pipefail]

run: when_changed

includes:
  client:tun2socks: ./client/go/Taskfile.yml

tasks:
  clean:
    deps:
      - client:tun2socks:clean
    cmds:
      - rm -rf .task

  addlicense:
    desc: Add missing license headers
    cmds:
      - go run github.com/google/addlicense@latest -c "The Outline Authors" -l apache -ignore 'output/**' -ignore 'node_modules/**' .
