version: '3'

set: [pipefail]

run: when_changed

includes:
  client:tun2socks: ./client/src/tun2socks/Taskfile.yml

tasks:
  clean:
    deps:
      - client:tun2socks:clean
    cmds:
      - rm -rf .task
