#! /bin/bash
# Copyright 2024 The Outline Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

function main {
    local binary="$(dirname $0)/gobind-unpatched"
    declare -a args=()
    for arg in "$@"; do
        if [[ "$arg" =~ "--tags=*maccatalyst*" ]]; then
            # Workaround for https://github.com/golang/go/issues/52299.
            # Fix based on https://github.com/stffabi/go-mobile/commit/e31230fb8e5d45adb0be5b69854b6b9bafb8151f.
            echo "Patching environment for maccatalyst"
            export GOOS=ios
            args+=("-tags=macos,maccatalyst")
        else 
            args+=("$arg")
        fi
    done
    "$binary" "${args[@]}"
}

main "$@"
