/*
 * Copyright 2023 The Outline Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


// Objective-C API for talking to the following Go packages
//
//	github.com/Jigsaw-Code/outline-go-tun2socks/outline/apple
//	github.com/Jigsaw-Code/outline-go-tun2socks/outline/shadowsocks
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Tun2socks_FRAMEWORK_H__
#define __Tun2socks_FRAMEWORK_H__

#include "Tun2socks.objc.h"
#include "Shadowsocks.objc.h"
#include "Universe.objc.h"

#endif
