# Copyright 2018 The Outline Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

platform :ios do
  lane :debug do |options|
    automatic_code_signing(
      use_automatic_signing: true,
      team_id: ENV["APPLE_DEV_PORTAL_TEAM_ID"],
      code_sign_identity: "iPhone Developer"
    )

    build_outline
  end

  lane :release do |options|
    xcodeproj = "Outline.xcodeproj"

    match(
      type: "appstore",
      readonly: true,
      app_identifier: [
        "org.outline.ios.client",
        "org.outline.ios.client.VpnExtension"
      ]
    )

    disable_automatic_code_signing(path: xcodeproj)

    update_project_provisioning(
      xcodeproj: xcodeproj,
      profile: ENV["sigh_org.outline.ios.client_appstore_profile-path"],
      target_filter: ".*Outline.*",
      build_configuration: "Release"
    )

    update_project_provisioning(
      xcodeproj: xcodeproj,
      profile: ENV["sigh_org.outline.ios.client.VpnExtension_appstore_profile-path"],
      target_filter: ".*VpnExtension.*",
      build_configuration: "Release"
    )

    package(local: options[:local])
  end
end

platform :mac do
  lane :debug do |options|
    build_outline
  end

  lane :release do |options|
    # TODO: signing?

    package(local: options[:local])
  end
end

def build_outline
  build_app(
    scheme: "Outline",
    export_xcargs: "-allowProvisioningUpdates"
  )
end
