# Copyright 2018 The Outline Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

platform :ios do
  desc "Build a Develompent-signed iOS client"
  lane :build_debug do |options|
    configure_environment(:ios, :debug)
    build_outline
  end

  desc "Build a Appstore-signed iOS client"
  lane :build_release do |options|
    configure_environment(:ios, :release)
    build_outline
  end
end

platform :mac do
  desc "Build a Develompent-signed MacOS client"
  lane :build_debug do |options|
    configure_environment(:mac, :debug)
    build_outline
  end

  desc "Build a Appstore-signed MacOS client"
  lane :build_release do |options|
    configure_environment(:mac, :release)
    build_outline
  end
end

# Configures code signing and provisioning in the xcode project.
def configure_environment(platform, buildMode)
  if !ENV["CI"] then
    return configure_automatic_code_signing(platform, buildMode)
  end

  setup_ci
  get_signing_credentials_and_provisioning_profiles(platform, buildMode)

  xcodeproj = "Outline.xcodeproj"
  case buildMode
  when :debug
    build_configuration = "Development"
    profile_path = "development"
  when :release
    build_configuration = "Release"
    profile_path = "appstore"
  else
    build_configuration = "Development"
    profile_path = "development"
  end

  update_project_provisioning(
    xcodeproj: xcodeproj,
    profile: ENV["sigh_org.outline.#{platform}.client_#{profile_path}_profile-path"],
    target_filter: ".*Outline.*",
    build_configuration: build_configuration
  )
  
  update_project_provisioning(
    xcodeproj: xcodeproj,
    profile: ENV["sigh_org.outline.#{platform}.client.VpnExtension_#{profile_path}_profile-path"],
    target_filter: ".*VpnExtension.*",
    build_configuration: build_configuration
  )
end

def configure_automatic_code_signing(platform, buildMode)
  # case platform
  # when :ios
  #   title_case = "iOS"
  # when :mac
  #   title_case = "MacOS"
  # else
  #   title_case = platform
  # end

  update_code_signing_settings(
    use_automatic_signing: buildMode == :debug,
    path: "Outline.xcodeproj",
    team_id: ENV["APPLE_DEV_PORTAL_TEAM_ID"],
    code_sign_identity: "Apple Development"
  )
end

def get_signing_credentials_and_provisioning_profiles(platform, buildMode)
  case buildMode
  when :debug
    certificate_type = "development"
  when :release
    certificate_type = "appstore"
  else
    certificate_type = "development"
  end

  match(
    type: certificate_type,
    readonly: true,
    app_identifier: [
      "org.outline.#{platform}.client",
      "org.outline.#{platform}.client.VpnExtension"
    ]
  )
end

def build_outline
  build_app(scheme: "Outline", export_xcargs: "-allowProvisioningUpdates")
end
