version: '3'

vars:
  # This needs to be updated if the file moves.
  # TODO: Output to $REPO_ROOT/output/client/tun2socks instead.
  OUT_DIR: '{{joinPath .TASKFILE_DIR "../../output/build"}}'
  BIN_DIR: "{{.OUT_DIR}}/build"
  MOBILE_PKG: "{{.TASKFILE_DIR}}/outline/tun2socks"
  GOMOBILE_BIND_CMD: "env PATH=\"{{.BIN_DIR}}:${PATH}\" '{{.BIN_DIR}}/gomobile' bind -ldflags='-s -w'"

tasks:
  electron:
    desc: "Build the tun2socks binary for Electron platforms"
    internal: true
    requires: {vars: [TARGET_OS]}
    vars:
      # TODO(fortuna): remove this, it's not really needed since we don't release it separately anymore.
      TUN2SOCKS_VERSION: "v1.16.11"
      OUTPUT: '{{.OUT_DIR}}/{{.TARGET_OS}}/tun2socks{{if eq .TARGET_OS "windows"}}.exe{{end}}'
    cmds:
      - rm -rf "{{dir .OUTPUT}}" && mkdir -p "{{dir .OUTPUT}}"
      # Linker flags: https://pkg.go.dev/cmd/link
      # -s Omit the symbol table and debug information.
      # -w Omit the DWARF symbol table.
      # -X Set the value of the string variable.
      - |
        {{if ne OS "{{.TARGET_OS}}"}}GOOS={{.TARGET_OS}} GOARCH=amd64 CGO_ENABLED=1 CC='zig cc -target x86_64-{{.TARGET_OS}}'{{end}} \
        go build -trimpath -ldflags="-s -w -X=main.version={{.TUN2SOCKS_VERSION}}" -o '{{.OUTPUT}}' '{{.TASKFILE_DIR}}/outline/electron'

  windows:
    desc: "Build the tun2socks binary for Windows"
    cmds: [{task: electron, vars: {TARGET_OS: "windows"}}]

  linux:
    desc: "Build the tun2socks binary for Linux"
    cmds: [{task: electron, vars: {TARGET_OS: "linux"}}]

  android:
    desc: "Build the tun2socks.aar library for Android"
    vars:
      TARGET_DIR: "{{.OUT_DIR}}/android"
    preconditions:
      - sh: '[[ -d "$ANDROID_HOME" ]]'
        msg: "Must set ANDROID_HOME"
      - sh: '[[ -d "$ANDROID_NDK" ]]'
        msg: "Must set ANDROID_NDK"
    cmds:
      - rm -rf "{{.TARGET_DIR}}" && mkdir -p "{{.TARGET_DIR}}"
      # -androidapi should match the minSdkVersion that the Android client supports.
      - "{{.GOMOBILE_BIND_CMD}} -target=android -androidapi 22 -o '{{.TARGET_DIR}}/tun2socks.aar' '{{.TASKFILE_DIR}}/outline/tun2socks' '{{.TASKFILE_DIR}}/outline/shadowsocks'"
    deps: ["gomobile"]

  ios-only:
    desc: "Build the Tun2socks.xcframework library for iOS only"
    internal: true
    vars:
      TARGET_DIR: '{{.OUT_DIR}}/ios'
    cmds:
      - rm -rf "{{.TARGET_DIR}}" && mkdir -p "{{.TARGET_DIR}}"
      # -iosversion should match the target version that the iOS client supports.
      - "{{.GOMOBILE_BIND_CMD}} -target=ios,iossimulator -iosversion=12.0 -bundleid org.outline.tun2socks -o '{{.TARGET_DIR}}/Tun2socks.xcframework' '{{.TASKFILE_DIR}}/outline/tun2socks' '{{.TASKFILE_DIR}}/outline/shadowsocks'"
    deps: ["gomobile"]

  macos-only:
    desc: "Build the Tun2socks.xcframework library for macOS only"
    internal: true
    vars:
      TARGET_DIR: '{{.OUT_DIR}}/macos'
    cmds:
      - rm -rf "{{.TARGET_DIR}}" && mkdir -p "{{.TARGET_DIR}}"
      # MACOSX_DEPLOYMENT_TARGET and -iosversion should match the versions that the macOS client supports.
      - export MACOSX_DEPLOYMENT_TARGET=10.14; {{.GOMOBILE_BIND_CMD}} -target=macos,maccatalyst -iosversion=13.1 -bundleid org.outline.tun2socks -o '{{.TARGET_DIR}}/Tun2socks.xcframework' '{{.TASKFILE_DIR}}/outline/tun2socks' '{{.TASKFILE_DIR}}/outline/shadowsocks'
    deps: ["gomobile"]

  apple:
    desc: "Build combined Tun2socks.xcframework library for Apple platforms"
    aliases: [ios, macos, maccatalyst]
    vars:
      TARGET_DIR: '{{.OUT_DIR}}/apple'
    cmds:
      - rm -rf "{{.TARGET_DIR}}" && mkdir -p "{{.TARGET_DIR}}"
      - |
        find '{{.OUT_DIR}}/macos/Tun2socks.xcframework' '{{.OUT_DIR}}/ios/Tun2socks.xcframework' -name "Tun2socks.framework" -type d |
        xargs -I {} echo " -framework {} " |
        xargs xcrun xcodebuild -create-xcframework -output '{{.TARGET_DIR}}/Tun2socks.xcframework'
    deps: ["ios-only", "macos-only"]

  browser:
    desc: "Placeholder for the browser build. Does nothing"
  
  gomobile:
    desc: "Build Go Mobile"
    internal: true
    cmds:
      - mkdir -p "{{.BIN_DIR}}"
      - go build -o "{{.BIN_DIR}}" golang.org/x/mobile/cmd/gomobile golang.org/x/mobile/cmd/gobind
    sources: ["{{.REPO_ROOT}}/go.sum"]
    generates: ["{{.BIN_DIR}}/gomobile", "{{.BIN_DIR}}/gobind"]

  clean:
    cmds:
      - rm -r "{{.REPO_ROOT}}/output/client/tun2socks" .task
      - go clean -i -r '{{.TASKFILE_DIR}}/outline/tun2socks' '{{.TASKFILE_DIR}}/outline/shadowsocks'
