# Copyright 2024 The Outline Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Build and Test / Manager

concurrency:
  group: '${{ github.head_ref || github.ref }} Manager'
  cancel-in-progress: true

on:
  pull_request:
    types:
      - opened
      - synchronize
  push:
    branches:
      - master
  schedule:
    - cron: "0 13 * * *"  # Run daily at 1PM UTC.

jobs:
  web_test:
    name: Web Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: npm
          cache-dependency-path: ./server_manager/package.json

      - name: Install NPM Dependencies
        run: npm ci

      - name: Manager Web Test
        run: npm run action server_manager/test

  linux_debug_build:
    name: Linux Debug Build
    runs-on: ubuntu-latest
    needs: web_test
    env:
      SENTRY_DSN: debug
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: npm
          cache-dependency-path: ./server_manager/package.json

      - name: Install NPM Dependencies
        run: npm ci

      - name: Build Linux Manager
        run: npm run action server_manager/electron/build linux

      # Since Linux doesn't require signing, we can use it to smoke test the package action
      - name: Smoke Test Linux Manager Package
        run: npm run action server_manager/electron/package linux -- --buildMode=release --versionName=1.0.0

  windows_debug_build:
    name: Windows Debug Build
    # TODO(daniellacosse): port bash scripts to windows so we can build the manager on windows
    runs-on: ubuntu-latest
    needs: web_test
    env:
      SENTRY_DSN: debug
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: npm
          cache-dependency-path: ./server_manager/package.json

      - name: Install NPM Dependencies
        run: npm ci

      - name: Build Windows Manager
        run: npm run action server_manager/electron/build windows

  mac_debug_build:
    name: MacOS Debug Build
    runs-on: macos-13
    needs: web_test
    env:
      SENTRY_DSN: debug
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: npm
          cache-dependency-path: ./server_manager/package.json

      - name: Install NPM Dependencies
        run: npm ci

      - name: Build MacOS Manager
        run: npm run action server_manager/electron/build macos
