name: Build Client Linux Release Candidate

on: [workflow_dispatch, workflow_call]

jobs:
  build_client_linux_release_candidate:
    name: Build Client Linux Release Candidate
    runs-on: ubuntu-20.04
    timeout-minutes: 15
    env:
      SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Install Node
        uses: actions/setup-node@v2.2.0
        with:
          node-version: 16

      - name: Install NPM Dependencies
        run: npm ci

      - name: Build Linux Release Candidate
        run: npm run action src/electron/build linux -- --buildMode=release

      - name: Upload Linux Release Candidate
        uses: actions/upload-artifact@v2
        with:
          name: client_linux_release_${{ github.sha }}
          path: build/dist
          if-no-files-found: error
