name: Build Windows Unsigned Release Candidate

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      SENTRY_DSN:
        required: true

jobs:
  windows_release_build:
    name: Build and Pack Windows Unsigned Release Installer
    runs-on: windows-latest
    timeout-minutes: 10
    env:
      SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
    steps:
      - name: Support longpaths
        run: git config --system core.longpaths true

      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Install Node
        uses: actions/setup-node@v2.2.0
        with:
          node-version: 16

      - name: Install NPM Dependencies
        run: npm ci

      - name: Build Windows Installer
        run: npm run action src/electron/build windows -- --buildMode=release

      - name: Upload Windows Installer
        uses: actions/upload-artifact@v2
        with:
          name: client_installer_unsigned_windows_release_${{ github.sha }}
          path: build/dist
          if-no-files-found: error
