name: Build and Test / Infrastructure

concurrency:
  group: '${{ github.head_ref || github.ref }} Infrastructure'
  cancel-in-progress: true

on:
  pull_request:
    types:
      - opened
      - synchronize
  push:
    branches:
      - master

jobs:
  test:
    name: Infrastructure Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: npm
          cache-dependency-path: ./infrastructure/package.json

      - name: Install NPM Dependencies
        run: npm ci

      - name: Infrastructure Test
        run: npm run action infrastructure/test
